// @ts-check
import js from "@eslint/js";
import globals from "globals";
import tseslint from "typescript-eslint";
import reactHooks from "eslint-plugin-react-hooks";

/**
 * ESLint exists here for one job above all others: to enforce the layering
 * CLAUDE.md already mandates but nothing ever checked.
 *
 * "State Management: Custom hooks in src/app/hooks/ handle data fetching and
 * mutation logic. Keep page components presentational." That rule was written
 * down and then broken in 22 files, because a written rule with no check is a
 * suggestion. The `no-restricted-imports` block below turns it into a build
 * error for new code.
 *
 * DELIBERATELY NOT A BIG BANG
 * ---------------------------
 * This config is tuned so `pnpm lint` passes today. A linter introduced into a
 * mature codebase with every recommended rule on produces hundreds of findings,
 * gets a blanket --no-verify, and is dead within a week. So:
 *
 *   - Rules that catch real bugs (react-hooks, no-case-declarations, the
 *     layering boundary) are errors.
 *   - Rules that describe known, tracked debt -- `any` at the Supabase
 *     boundary, chiefly -- are warnings. There are 207 of them and they are
 *     not fixed by a lint rule; they are fixed by typing the client with
 *     <Database>, which src/lib/supabaseClient.ts explains is its own piece of
 *     work with its own blast radius.
 *
 * Tighten warnings to errors as each category reaches zero, not before.
 */
export default tseslint.config(
  {
    // Generated, vendored, or not ours.
    ignores: [
      "dist/**",
      "build/**",
      "node_modules/**",
      "android/**",
      "ios/**",
      "supabase/**", // Deno runtime, different globals and module resolution
      "src/types/database.types.ts", // generated by `supabase gen types`
      "src/app/components/ui/**", // shadcn/Radix, upstream-owned
      "worker-engine/**",
      "fastapi-gateway/**",
      ".understand-anything/**", // third-party tooling cache, not source
      "*.config.js",
      "*.config.ts",
    ],
  },

  // Node scripts: build tooling, seeders and one-off queries. They run under
  // Node, not the browser, so `process`, `console` and friends are defined.
  // Without this they produce ~90 phantom no-undef errors and drown the real
  // findings — which is how a linter gets switched off.
  {
    files: ["scripts/**/*.{js,mjs,cjs}", "*.{js,mjs,cjs}"],
    languageOptions: {
      globals: { ...globals.node },
    },
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,

  {
    files: ["src/**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2022,
      globals: { ...globals.browser, ...globals.es2022 },
    },
    plugins: {
      "react-hooks": reactHooks,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,

      // Known, tracked debt — see the header. Visible, not blocking.
      "@typescript-eslint/no-explicit-any": "warn",
      "@typescript-eslint/no-unused-vars": [
        "warn",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
      // tsc already enforces this far more precisely via `strict`.
      "@typescript-eslint/no-empty-object-type": "off",
    },
  },

  // -------------------------------------------------------------------------
  // The layering boundary.
  //
  // Pages and components must not talk to Supabase directly. They compose;
  // hooks fetch. This is CLAUDE.md's rule, enforced.
  //
  // Scoped to pages/ and components/ rather than applied globally and then
  // excepted, so the allowed callers stay explicit: src/app/hooks/**,
  // src/lib/**, src/utils/**, and src/app/App.tsx (session bootstrap).
  //
  // The 22 existing violations are grandfathered below. This rule stops the
  // 23rd; it does not pretend the first 22 are fixed.
  // -------------------------------------------------------------------------
  {
    files: ["src/app/pages/**/*.{ts,tsx}", "src/app/components/**/*.{ts,tsx}"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: ["**/lib/supabaseClient", "@/lib/supabaseClient"],
              message:
                "Pages and components must not query Supabase directly. Put the query in a hook under src/app/hooks/ and consume that — see CLAUDE.md, 'State Management'.",
            },
            {
              group: ["@supabase/supabase-js"],
              message:
                "Import the shared client from src/lib/supabaseClient via a hook. A second createClient() means a second auth session.",
            },
          ],
        },
      ],
    },
  },

  // -------------------------------------------------------------------------
  // Grandfathered: files that already bypass the hooks layer.
  //
  // Each one predates the rule. Delete its entry when the file is converted —
  // the list shrinking is the migration's progress bar. Do not add to it.
  // -------------------------------------------------------------------------
  {
    files: [
      "src/app/pages/admin/AdminExperiences.tsx",
      "src/app/pages/admin/AdminItemForm.tsx",
      "src/app/pages/admin/AdminMerchantPreview.tsx",
      "src/app/pages/admin/AdminShops.tsx",
      "src/app/pages/merchant/MerchantCollections.tsx",
      "src/app/pages/MerchantOnboarding.tsx",
      "src/app/pages/PostDetail.tsx",
      "src/app/pages/public/GiftPage.tsx",
      "src/app/pages/public/Login.tsx",
      "src/app/pages/sender/Confirmation.tsx",
      "src/app/pages/sender/ItemDetail.tsx",
      "src/app/pages/sender/OrderDashboard.tsx",
      "src/app/pages/sender/OrderDetail.tsx",
      "src/app/pages/ShopDirectory.tsx",
      "src/app/components/layout/Header.tsx",
      "src/app/components/messaging/QuotationBuilder.tsx",
      "src/app/components/messaging/QuotationCard.tsx",
      "src/app/components/shared/CartSlider.tsx",
      "src/app/components/shared/NotificationSlider.tsx",
      "src/app/components/shared/PulseStrip.tsx",
      "src/app/components/shared/WalletLedgerView.tsx",
      "src/app/components/storefront/ItemQuickView.tsx",
    ],
    rules: {
      "no-restricted-imports": "off",
    },
  },
);
