/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "bllymuyxnbnkcutnxcek"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJsbHltdXl4bmJua2N1dG54Y2VrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg0NjkzMjIsImV4cCI6MjA5NDA0NTMyMn0.TMx72yWyF5d-CSN2JuJgadhuc-SOgzcoeWAGbf_oDiw"